### ISSUE TITLE
ERROR in ./node_modules/ng-brazil/esm5/ng-brazil.js

### ISSUE THREAD

**Issue by EliasSimoes** [mariohmol/ng-brazil#10]
Ao tentar utilizar o MASKS me deparei com esses erros.

**ERROR in ./node_modules/ng-brazil/esm5/ng-brazil.js
Module not found: Error: Can't resolve 'text-mask-addons/dist/createNumberMask' in 'YOUR_NODE_MODULES_PATH'.**

Detalhe: já importei os modulos 
import { **NgBrazil** } from 'ng-brazil';
import { **TextMaskModule** } from 'angular2-text-mask';

imports: [
   ...
    **NgBrazil,
    TextMaskModule**
    ...
  ]

A instalação dos pacotes foi feita através do comando: **npm install --save ng-brazil angular2-text-mask**

**Comment by mariohmol** [comment]
uhmmmm c vc usa um `npm i text-mask-addons` funciona?

**Comment by mariohmol** [comment]
subi  a versao 0.6.1, consegue testar com ela pf?

**Comment by EliasSimoes** [comment]
Vou testar agora mesmo e já te passo o feedback.

Desde já, muito obrigado pela força.

**Comment by EliasSimoes** [comment]
Deu certo sim. Muito obrigado e abraço!!!

**Comment by mariohmol** [comment]
Deu certo subindo a versao ou instalando o modulo text-mask-addons ?
