### ISSUE TITLE
Can't resolve 'text-mask-addons/dist/createNumberMask'

### ISSUE THREAD

**Issue by luidiva** [mariohmol/ng-brazil#13]
EU precisei adicionar este modulo. Não encontrei na documentação, seria legal adicionar.

**Comment by mariohmol** [comment]
Hi.. can u try this:  `npm install --save ng-brazil angular2-text-mask`

**Comment by luidiva** [comment]
Actually I had to install npm i text-mask-addons --save.

**Comment by luidiva** [comment]
Question: can I use this with two-way binding?

**Comment by mariohmol** [comment]
Hi .. thanks for that! I updated the readme.. i think it works with ngModel and forms.. is that what you asked?
