### ISSUE TITLE
Inscrição Estadual - Doubt

### ISSUE THREAD

**Issue by woj1965** [mariohmol/ng-brazil#16]
Hello, 
I trying to validate Inscrição Estadual, don't matter with state I choose the results is the same.
This package detects the state based on Inscrição Estadual number?

Another thing, the Amazonas State has now a format mask 99.999.999-9.

Thanks for the package.

**Comment by mariohmol** [comment]
Awesome catch..

u need a amazon state? can do it now.. its other you need?

**Comment by mariohmol** [comment]
Hi.. we just release a versionl 0.6.2 with a amazon example and following your pattern.

You can see the demo working here!

https://stackblitz.com/edit/ng-brazil

Thanks

**Comment by woj1965** [comment]
Yes I need it, but is for the other people too.

**Comment by woj1965** [comment]
This package detects the state based on Inscrição Estadual number?

**Comment by mariohmol** [comment]
Is this what u expected?

**Comment by woj1965** [comment]
Yes, it is.
I developing a app where people of many Brazilian States may fill a application form and it is very good test & mask some government identification number.
