### ISSUE TITLE
More Brazilian States Inscrição Estadual Masks

### ISSUE THREAD

**Issue by woj1965** [mariohmol/ng-brazil#17]
Consulting the site http://www.sintegra.gov.br/insc_est.html, I found some more masks for Inscrição Estadual. I not check if the validation calculation remains the same in your code, yet.

**Masks**:
- AP 999999999
- DF 99 999999 999-99
- GO 99.999.999-9
- MS 999999999
- MT 9999999999-9
- PB 99999999-9
- PR 99999999-99
- RJ 99.999.99-9
- SC 999.999.999
- TO 99 99 9999999

**Comment by mariohmol** [comment]
Awesome!! I'm making this now.. can u help and check if the others that we have there is correct?

https://github.com/mariohmol/ng-brazil/blob/master/ng-brazil/src/core/inscricaoestadual.ts#L595

**Comment by woj1965** [comment]
> Awesome!! I'm making this now.. can u help and check if the others that we have there is correct?
> 
> https://github.com/mariohmol/ng-brazil/blob/master/ng-brazil/src/core/inscricaoestadual.ts#L595

I'll do this right now.

**Comment by mariohmol** [comment]
yes.. doing that now kkkk

**Comment by woj1965** [comment]
There are 3 changes:
- MG 999.999.999/9999
- PA 99-999999-9
- RN 99.999.999-9X (the last digit is optional there are 2 calculation formulas)

**Comment by mariohmol** [comment]
Thank you!

Just released version 0.6.3 with this and updated demo

https://stackblitz.com/edit/ng-brazil

**Comment by woj1965** [comment]
Updated my project, thanks.
