### ISSUE TITLE
Mobile phone mask

### ISSUE THREAD

**Issue by woj1965** [mariohmol/ng-brazil#21]
Hello,
how can I mask & validate the Brazilian mobile phones with 9 and 8 digits?

**Comment by mariohmol** [comment]
This is a good question.. we need to find out what state has the 9 digits already... 

I separated this project in 2.. one to have all the br rules and here will be just a angular wrapper

https://github.com/mariohmol/js-brasil

if u can help there as well will be awesome

**Comment by woj1965** [comment]
I found the image below in Anatel website.
It is a agenda of implementation of 9 digit for mobile phones.
Considering it, I guess all states already have it.
[http://www.anatel.gov.br/Portal/documentos/imagem/1412795477426.png](url)

Maybe you may create a separated mask/validation for mobile phones.

**Comment by mariohmol** [comment]
Hi.. I updated the project to contains more about phone numbers

https://github.com/mariohmol/js-brasil

**Comment by mariohmol** [comment]
ng-brazil v0.6.5

**Comment by mariohmol** [comment]
Update the way you should use it

```html
   <input id="mask-telefone" type="text" formControlName="telefone" telefone #telefone [textMask]="{mask: MASKS.telefone.textMaskFunction}">
```

**Comment by woj1965** [comment]
I getting the following message, when tasting the new version.

**node_modules/ng-brazil/ng-brazil has no exported member 'MASKS'**
