### ISSUE TITLE
Version 0.6.5 missing masks

### ISSUE THREAD

**Issue by woj1965** [mariohmol/ng-brazil#22]
Hello,
the new version 0.6.5 missing the masks, even your StackBlitz demo is not maskarating the fields.

**Comment by woj1965** [comment]
I found what was missing.

in the component.ts file is necessary install and import **js-brasil** package, and change MASKS constant.

import { utilsBr } from 'js-brasil';
const MASKS = utilsBr.MASKS;

**Comment by mariohmol** [comment]
Thanks!! Can u make a PR?

**Comment by woj1965** [comment]
I suggest some updates for separation of telefone and celular masks/validations.
I don't know if create a pool request is necessary.

**Comment by mariohmol** [comment]
fixed on 0.7.1 thanks
