### ISSUE TITLE
suporte para angular 7

### ISSUE THREAD

**Issue by dayvesoliveira** [mariohmol/ng-brazil#28]
Estou tentando atualizar a versão do angular para a 7, mas estou com problemas com essa lib.

chunk {vendor} vendor.js, vendor.js.map (vendor) 7.05 MB [initial] [rendered]

ERROR in ./node_modules/ng-brazil/esm5/ng-brazil.js
Module not found: Error: Can't resolve 'js-brasil' in 'C:\development\frontend\jretail-loja-front\node_modules\ng-brazil\esm5'
ERROR in ./node_modules/ng-brazil/esm5/ng-brazil.js
Module not found: Error: Can't resolve 'js-brasil/src/utils' in ...\node_modules\ng-brazil\esm5'
i ｢wdm｣: Failed to compile.

 npm install --save ng-brazil angular2-text-mask
npm WARN ng-brazil@0.7.8 requires a peer of @angular/core@>=4.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-brazil@0.7.8 requires a peer of @angular/common@>=4.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-brazil@0.7.8 requires a peer of js-brasil@>=1.1.8 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by mariohmol** [comment]
uhmmm deixa eu atualizar aq..

**Comment by mariohmol** [comment]
subi na versao 0.7.9!

vlw!

**Comment by dayvesoliveira** [comment]
Opa, obrigado.

Em qua, 26 de dez de 2018 12:10, Mario Mol <notifications@github.com
escreveu:
