### ISSUE TITLE
Usar máscara sem FormControl

### ISSUE THREAD

**Issue by btd1337** [mariohmol/ng-brazil#29]
@mariohmol Primeiramente, parabéns por este ótimo trabalho, gostaria de tirar uma dúvida: 

É possível usar a máscara sem Formcontrol? Obtendo o valor através de [value]?

```
<input
      matInput
      type="text"
      [value]="cooperator?.person?.document"
      cpf
      [textMask]="{ mask: MASKS.cpf.textMask }"
      readonly
 />
```

**Comment by mariohmol** [comment]
Desculpe só vi sua issue agora...
tentou com ngmodel? `([ngModel])`

**Comment by btd1337** [comment]
Não, mas irei tentar. Novamente obrigado!

**Comment by mariohmol** [comment]
funfou?
