### ISSUE TITLE
Number Pipe decimais

### ISSUE THREAD

**Issue by adelcioml** [mariohmol/ng-brazil#32]
Olá,
ao usar o NgBrazil eu notei que o number pipe fixa as decimais em 2 sempre e também os valores 

24,10 fica 24,1.
Eu queria saber como que usa o number pipe pelo NgBrazil, já que ele de algum modo sobrescreve o number pipe do angular...

O que eu preciso é formatar um número com 6 decimais tipo: {{ valor | number:'0.6-6' }} isso funcionava antes de eu instalar o NgBrazil..

Grato

**Comment by mariohmol** [comment]
putz.. verdade.. usa o mesmo nome.. vou alterar aqui

**Comment by mariohmol** [comment]
liberei no 1.2.6

agora ficou {{'123.23' | numberBrazil}} 

vlw

**Comment by adelcioml** [comment]
Ah sim... hehe... 
excelente projeto... 
:)

**Comment by mariohmol** [comment]
vlw.. tem muita coisa p fazer nele ainda.. mas vamo andando =)

**Comment by adelcioml** [comment]
Bom dia Mário, aproveitando eu acho que o currency está com o mesmo
problema do number... ele está sobrescrevendo o do angular e ficando
assim...

R$ 32,9 ao invés de R$ 32,90 ... por exemplo...

Não sei se você muda para currencyBrazil ou me informa como usar ele... ok

abraços

**Comment by mariohmol** [comment]
coloquei currencyBrazil na 1.2.7

vlw!
