### ISSUE TITLE
currency problems

### ISSUE THREAD

**Issue by DeraldoSilva** [mariohmol/ng-brazil#33]
Hi.
In the stackblitz example (https://stackblitz.com/edit/ng-brazil?file=src%2Fapp%2Fapp.component.ts) in the app.component.html, line 109, instead checking the currency errors, is checking the "cep" errors. With it fixed, when the example value is typed (1234,56) and submited,  it returns "Errors found: currency true". 
why that? What am I missing?

**Comment by mariohmol** [comment]
indeed.. the error is on js-brasil

we need to create a test case here 
https://github.com/mariohmol/js-brasil/blob/master/test/validate.ts

and double check this function
https://github.com/mariohmol/js-brasil/blob/master/src/validate.ts#L210

**Comment by mariohmol** [comment]
fixed in latest version!

thanks
