### ISSUE TITLE
Angular 9 errors

### ISSUE THREAD

**Issue by duard** [mariohmol/ng-brazil#34]
This package do not work with Angualr 9 rc-3

`ERROR in /home/duard/x-projects/app.sigpharma.xyz/nx-Solucoes/node_modules/js-brasil/dist/index.js
Module not found: Error: Can't resolve './src/estados' in '/home/duard/x-projects/app.sigpharma.xyz/nx-Solucoes/node_modules/js-brasil/dist'
ERROR in /home/duard/x-projects/app.sigpharma.xyz/nx-Solucoes/node_modules/js-brasil/dist/index.js
Module not found: Error: Can't resolve './src/faker' in '/home/duard/x-projects/app.sigpharma.xyz/nx-Solucoes/node_modules/js-brasil/dist'
ERROR in /home/duard/x-projects/app.sigpharma.xyz/nx-Solucoes/node_modules/js-brasil/dist/index.js
Module not found: Error: Can't resolve './src/mask' in '/home/duard/x-projects/app.sigpharma.xyz/nx-Solucoes/node_modules/js-brasil/dist'
ERROR in /home/duard/x-projects/app.sigpharma.xyz/nx-Solucoes/node_modules/js-brasil/dist/index.js
Module not found: Error: Can't resolve './src/placa' in '/home/duard/x-projects/app.sigpharma.xyz/nx-Solucoes/node_modules/js-brasil/dist'
ERROR in /home/duard/x-projects/app.sigpharma.xyz/nx-Solucoes/node_modules/js-brasil/dist/index.js
Module not found: Error: Can't resolve './src/utils' in '/home/duard/x-projects/app.sigpharma.xyz/nx-Solucoes/node_modules/js-brasil/dist'
ERROR in /home/duard/x-projects/app.sigpharma.xyz/nx-Solucoes/node_modules/js-brasil/dist/index.js
Module not found: Error: Can't resolve './src/validate' in '/home/duard/x-projects/app.sigpharma.xyz/nx-Solucoes/node_modules/js-brasil/dist'
`

**Comment by jpnobregaster** [comment]
+1

**Comment by mariohmol** [comment]
Criei uma branch com o ang9 mas tem dado muito pau.. 

primeiro com `NullInjectorError: No provider for RendererFactory2!`, que ele nao esta achando o provider

e depois que tentei colocar o browsermodule deu outro erro, inclusive abri uma issue
https://github.com/angular/angular/issues/34355

se puderem ajudar de alguma forma

**Comment by mariohmol** [comment]
consegui, subi a versao ng-brazil@2.0.9 , conseguem testar ?

**Comment by mariohmol** [comment]
build passando com ang9, https://travis-ci.org/mariohmol/ng-brazil/builds/623899471

qualquer coisa reabre

**Comment by mariohmol** [comment]
@jpnobregaster @duard  ?
