### ISSUE TITLE
ionic support android 10

### ISSUE THREAD

**Issue by GravesDXD** [mariohmol/ng-brazil#36]
I want to know how the ionic3 project supports Android 10. I have downloaded the latest SDK29,and changed the config ToolsVersion to 29. but I found Android 10 mobile crash and is not compatible after downloaded and installed. but other Android  is ok, like Android  9. how to fix it. thanks a lot

**Comment by mariohmol** [comment]
vc fala que da erro usando o ng-brazil?

**Comment by GravesDXD** [comment]
sorry, I don't understand what do you mean?

**Comment by GravesDXD** [comment]
sorry, I don't understand what you mean?

**Comment by mariohmol** [comment]
sorry.. this is a module for brazillian apps.. note fully related with ionic
