### ISSUE TITLE
Validação de 111.111.111-11

### ISSUE THREAD

**Issue by richof** [mariohmol/ng-brazil#38]
Um CPF com 111.111.111-11 ou outros números repetidos, não estão sendo validado na ultima versão
Aqui a minha implementação

ngOnInit() {
   this.registroForm=this.fb.group({
     cpf:['',[Validators.required,NgBrazilValidators.cpf]]    
   });
 HTML:
 <input class="form-control" id="cpf" type="text" placeholder="CPF(obrigatorio)" formControlName="cpf"
                [textMask]="{mask:MASKS.cpf.textMask}">

**Comment by mariohmol** [comment]
obrigado, subi na 2.0.7

**Comment by mariohmol** [comment]
subi o ng brazil pro 1.4.7 com o jsbrasil2.x
