### ISSUE TITLE
Inscrição estadual da Bahia

### ISSUE THREAD

**Issue by LeandroSoares89** [mariohmol/ng-brazil#39]
A mascara da inscrição estadual da Bahia foi alterada de 8 caracteres para 9 ocasionando um erro.
sendo impossivel digitar o novo digito
segue link do sintegra da bahia
https://www.sefaz.ba.gov.br/contribuinte/informacoes_fiscais/doc_fiscal/calculodv.htm

**Comment by mariohmol** [comment]
fino esse link eihn?

temo q abrir uma issue aqui https://github.com/mariohmol/js-brasil

**Comment by mariohmol** [comment]
subi as correcoes na v2.3.13 - validators, mask e testes para IE da Bahia
