### ISSUE TITLE
Suport angular 9 

### ISSUE THREAD

**Issue by andrejm7** [mariohmol/ng-brazil#40]
npm WARN ng-brazil@1.4.7 requires a peer of @angular/core@>=4.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.  
npm WARN ng-brazil@1.4.7 requires a peer of @angular/common@>=4.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by mariohmol** [comment]
vê se essa versao funciona proc 2.0.10

senao pode reabrir

vlw

**Comment by andrejm7** [comment]
npm WARN ng-brazil@1.4.7 requires a peer of @angular/core@>=4.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.  
npm WARN ng-brazil@1.4.7 requires a peer of @angular/common@>=4.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.

amigo mesmo com a versão da isso ai

meu package.json esta assim
"ng-brazil": "^1.4.7",
"js-brasil": "^2.0.10",

**Comment by andrejm7** [comment]
??????????

**Comment by andrejm7** [comment]
agora deu isso amigo... o que é?

WARNING in Entry point 'ng-brazil' contains deep imports into 'C:/Projeto/node_modules/text-mask-core/dist/textMaskCore'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

**Comment by mariohmol** [comment]
Ola!

Isso é só um warning nao? no mais está funcionando?

**Comment by andrejm7** [comment]
suporte para o angular 10 agora hehe

**Comment by mariohmol** [comment]
Versão 2.2 com suporte a ang 10!

**Comment by mariohmol** [comment]
Foi mal mas deu muito bug na 9.. mas a deus foi redondon! vlw
