### ISSUE TITLE
Preciso permitir que um mesmo campo valide telefone e celular

### ISSUE THREAD

**Issue by rafahsborges** [mariohmol/ng-brazil#41]
@mariohmol ,
como eu faria para utilizar no mesmo campo o validador de telefone e celular?

**Comment by mariohmol** [comment]
Em tese funciona pros dois nao?

https://github.com/mariohmol/js-brasil/issues/38#issuecomment-623213868

**Comment by rafahsborges** [comment]
Pelo menos na versão que eu estava utilizando, quando queria ou tentava algo assim (61) 9 3...que seria um telefone fixo, ele bloqueia e só permite celular mesmo, que seria com 8 ou 9.

**Comment by mariohmol** [comment]
funcionando no stackblitz, https://stackblitz.com/edit/ng-brazil?file=src%2Fapp%2Fapp.component.ts

saca so
