### ISSUE TITLE
Warning: Entry point 'ng-brazil' contains deep imports into

### ISSUE THREAD

**Issue by andrejm7** [mariohmol/ng-brazil#43]
qual o problema?

Warning: Entry point 'ng-brazil' contains deep imports into 'C:/xxxxx/xxxxx-ui/node_modules/text-mask-core/dist/textMaskCore'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

**Comment by ruizuikeda** [comment]
Também estou com o mesmo problema:

````
"@angular/cli": "~10.0.3",
"@angular/compiler-cli": "^10.0.4",
"@angular/language-service": "^10.0.4",
"@angular-devkit/build-angular": "^0.1000.3",
````

**Comment by mariohmol** [comment]
Não é pq estavam rodando no angular 10 sendo q o modulo foi compilado pro 8?

tenta rodar com a versao 2.2 que é pra ang10 +

**Comment by mariohmol** [comment]
Aqui temos uma discussão a respeito
https://github.com/angular/angular/issues/35615 (angular + textmas) deve ser o mesmo problema

**Comment by mariohmol** [comment]
warning corrigidos na v2.2.5
