### ISSUE TITLE
máscara do telefone

### ISSUE THREAD

**Issue by andrejm7** [mariohmol/ng-brazil#45]
bom dia,
eu ainda não entendi como funciona a máscara do telefone... por exemplo olhem a imagem abaixo.
informa a máscara (31) **9**9999-9999 mas na hora de digitar aceita somente (31) 9999-9999

![image](https://user-images.githubusercontent.com/13546247/86929987-d83f0b00-c10c-11ea-9122-1b348f080dce.png)

exemplo no stackblitz
https://stackblitz.com/edit/ng-brazil-dmewxg

**Comment by mariohmol** [comment]
Corrigido o erro no stackblitz the demo.. o erro estava no textMask:  `[textMask]="{mask: MASKS.telefone.textMaskFunction}"`
