### ISSUE TITLE
Máscara para moeda

### ISSUE THREAD

**Issue by valmirbispo** [mariohmol/ng-brazil#46]
**Describe the bug**
Na máscara para moeda (currency) somente tem ponto. Não acrescenta a virgula.

**Meu código**
![Screenshot_3](https://user-images.githubusercontent.com/1265459/91646848-3364ee00-ea2a-11ea-803e-8401d4c629a1.png)

**No live exemple**
![Screenshot_1](https://user-images.githubusercontent.com/1265459/91646865-57283400-ea2a-11ea-8ad2-98bf8d3363fd.png)

**Comment by mariohmol** [comment]
A máscara aparece quando você coloca a vírgula.. no geral fica mais prático

Mas se quiser um monetário que venha com ,00 já no início, pode-ser feita uma conf nesse field de telefone

**Comment by valmirbispo** [comment]
Tranquilo. Percebi logo depois.
Só acontece que o padrão das máscara que vemos por aí é a parte decimal já ser exibida.
Mas desta forma fica bem prático também. Muito bom.

Parabéns pelo ótimo trabalho de vocês.
