### ISSUE TITLE
npm WARN ng-brazil@2.2.0 requires a peer of 

### ISSUE THREAD

**Issue by andrejm7** [mariohmol/ng-brazil#47]
daii Mario, corrige essa bronquinha pra gente ai.. valeu..

npm WARN ng-brazil@2.2.0 requires a peer of @angular/core@>=8.0.0 <10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-brazil@2.2.0 requires a peer of @angular/common@>=8.0.0 <10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-brazil@2.2.0 requires a peer of @angular/platform-browser@>=8.0.0 <10.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by mariohmol** [comment]
oops.. faltou isso.. versao 2.2.1
