### ISSUE TITLE
currencyBrazil com números negativos

### ISSUE THREAD

**Issue by halfs2** [mariohmol/ng-brazil#48]
Quando eu tenho um decimal ou string com o número negativo, por exemplo -190, na hora de formatar com o pipe ele deixa o valor 'positivo', sem o sinal de menos, era pra ser assim mesmo o comportamento ?

**Comment by mariohmol** [comment]
sabe que nem pensei nesse fluxo.. nem foi incluído testes e código pra isso..

pra funcionar é preciso fazer um test aqui:
https://github.com/mariohmol/js-brasil/blob/master/test/validate.ts#L163

e em masks:
https://github.com/mariohmol/js-brasil/blob/master/test/mask.ts#L107

Além dos respectivos source
* https://github.com/mariohmol/js-brasil/blob/master/src/validate.ts#L327
* https://github.com/mariohmol/js-brasil/blob/master/src/mask.ts#L68

Se puder colaborar, mão é difícil de fazer funcionar

**Comment by halfs2** [comment]
enviei uma pull request pra aceitar números negativos

**Comment by mariohmol** [comment]
normalmente só de instalar o js-brasil mais novo funciona, mas eu subi uma versão nova

valeu demais!
