### ISSUE TITLE
Currency pipe com tipos number

### ISSUE THREAD

**Issue by halfs2** [mariohmol/ng-brazil#49]
Percebi esse comportamento do currency com tipos númericos, por exemplo se eu tenho uma propriedade do tipo number com valor 0 (ZERO) e uso o pipe {{ valor | currencyBrazil }} eu esperaria que imprimisse no meu html algo assim R$ 0,00 mas ele não imprime nada, fica vazio, inclusive olhando no html fica sem informação nenhuma na tag. Outra coisa que acontece é que quando tenho um zero a direita ele também nunca é exibido, por exemplo R$ 25,50 é fica R$ 25,5

**Comment by mariohmol** [comment]
UHmm boa..
temos que ver primeiro no js-brasil .. da uma olhadinha aqui.. ve se consegue ajudar em algo

https://github.com/mariohmol/js-brasil/blob/master/test/mask.ts#L106

**Comment by halfs2** [comment]
Eu não esqueci isso aqui, to com pouco tempo ultimamente, mas assim que tiver um tempinho sobrando eu vou dar uma olhada nisso

**Comment by mariohmol** [comment]
Coloquei seus testes aq.. ve se era isso mesmo!

https://github.com/mariohmol/js-brasil/blob/master/test/mask.ts#L181

vlw
