### ISSUE TITLE
Seria possível não alterar o value do campo com a máscara?

### ISSUE THREAD

**Issue by rafastellato** [mariohmol/ng-brazil#50]
Armazenamos cnpjs de clientes sem formatação, por exemplo. Gostaria de saber se seria possível que, ao acessar o .Value desse campo, o valor fosse apenas com os números. 

Isso ajudaria tanto para salvar no banco, quanto para, por exemplo, um campo que pode ser CNPJ ou CPF e eu quero colocar uma máscara de acordo com a quantidade de caracteres que o usuário digitou. Não estou conseguindo isso hoje, pois ao obter o .length dessa forma:

![image](https://user-images.githubusercontent.com/3513950/95359817-f26dbe00-08a0-11eb-823a-93ad1b0c29a5.png)

Recebo 18 ao invés de 2. Procurei mas não achei nenhuma configuração. 

É possível? 

Muuuito obrigado

**Comment by mariohmol** [comment]
é.. faz um regex pra tirar os numeros pra salvar no banco.. e quando vem do banco, faz um ngIf que de acordo com o .length usa o mask pra cpf ou cnpj... ou um input pra cpf e outro pra cnpj... agora os dois juntos num input só tem q ser desenvolvido https://github.com/mariohmol/js-brasil/issues/15

**Comment by mariohmol** [comment]
vou fechar como dup do #11 .. se achar q é diferente pode reabrir
