### ISSUE TITLE
Campo monetário está limitado em R$ 9.999.999,99

### ISSUE THREAD

**Issue by josematheus10** [mariohmol/ng-brazil#52]
Campo monetário está limitado em R$ 9.999.999,99 

Digite: R$ 99.999.999,99 no campo monetário e o formulário não será validado 

Ao meu ver Deveria limitar apenas em R$ 999.999.999,99

**Comment by mariohmol** [comment]
Ola!

acho q tem q ser tratado no js-brasil

talvez isso?
https://github.com/mariohmol/js-brasil/blob/master/src/mask.ts#L74

Da pra criar uns case test aqui pra testar

https://github.com/mariohmol/js-brasil/blob/master/test/mask.ts#L107

**Comment by mariohmol** [comment]
@josematheus10 testei aq e parece q funcionou.. isso é relacionado a mascara? to meio perdido

**Comment by josematheus10** [comment]
Sim extamente isso https://github.com/mariohmol/js-brasil/blob/master/src/mask.ts#L74

**Comment by mariohmol** [comment]
mas saca so.. esse teste passa 
https://github.com/mariohmol/js-brasil/blob/master/test/mask.ts#L180

**Comment by mariohmol** [comment]
achei.. era n validate ne.. o regex de number tava bem ruim.. refiz aq.. vlw!

**Comment by josematheus10** [comment]
Obrigado! @mariohmol
