### ISSUE TITLE
Currency com 4 casas decimais

### ISSUE THREAD

**Issue by guilhermelima89** [mariohmol/ng-brazil#53]
Olá, gostaria de saber como utilizo 4 casas decimais após a vírgula.

Exemplo: R$ 1,3456 ou R$ 0,2233

**Comment by mariohmol** [comment]
Usando o numero dá pra vc?

https://github.com/mariohmol/ng-brazil/blob/master/src/app/demo/demo.component.html#L259

**Comment by mariohmol** [comment]
Veja se era isso mesmo:  https://github.com/mariohmol/js-brasil/blob/master/test/mask.ts#L177

**Comment by guilhermelima89** [comment]
Salve Mario,
O pipe ficou perfeito. Agora eu não consegui utilizar no textMask....
Obrigado
