### ISSUE TITLE
Definir número de casas decimais

### ISSUE THREAD

**Issue by evandro-mota** [mariohmol/ng-brazil#54]
É possível usar o numberBrazil definindo o número de casas decimais para exibir?
Tentei algo como no padrão  `number : '1.0-0'` ou `number : '1.2'`, mas não rolou.

**Comment by guilhermelima89** [comment]
Evandro tenta assim:

 {{ item.valor | currency: "BRL":true:"1.2-4" }}

**Comment by evandro-mota** [comment]
> Evandro tenta assim:
> 
> {{ item.valor | currency: "BRL":true:"1.2-4" }}

Meu problema é com números "normais" mesmo, não currency.

Tenho 1234 e queria exibir 1.234 porém o numberBrazil adiciona ,00 no final.

**Comment by mariohmol** [comment]
Vc fala algo tipo isso pra mascara?

https://github.com/mariohmol/js-brasil/blob/master/test/mask.ts#L141

**Comment by mariohmol** [comment]
Checa só a última versão vc consegue fazer isso

https://github.com/mariohmol/ng-brazil/blob/master/src/app/demo/demo.component.html#L259
