### ISSUE TITLE
Máscara para Porcentagem - Não funciona

### ISSUE THREAD

**Issue by JefersonDeSouza** [mariohmol/ng-brazil#58]
**Descreva o bug**
Máscara para porcentagem não funciona.

**Reproduzir**
Passos para reproduzir o comportamento:
1. Adicione ‘porcentagem [textMask]="{mask: MASKS.porcentagem.textMask}"’ no seu input text
2. Execute seu aplicativo
3. Veja o erro

**Comportamento esperado**
O comportamento esperado seria por exemplo 10 %, 30%, 100 %, ou 1.500 %, no entanto a máscara retorna nesse formato 10, 30, 100, 1.500.

**Capturas de tela**
 
![Screen Shot 03-23-21 at 02 22 PM](https://user-images.githubusercontent.com/25404751/112190361-af4f9f00-8be3-11eb-90d1-81629ba99595.PNG)

**Contexto adicional**
Angular CLI: 9.1.15
Node: 10.16.0
OS: win32 x64

Angular: 9.1.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.15
@angular-devkit/build-angular     0.901.15
@angular-devkit/build-optimizer   0.901.15
@angular-devkit/build-webpack     0.901.15
@angular-devkit/core              9.1.15
@angular-devkit/schematics        9.1.15
@angular/cli                      9.1.15
@angular/material                 9.2.4
@ngtools/webpack                  9.1.15
@schematics/angular               9.1.15
@schematics/update                0.901.15
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

**Desktop (preencha as seguintes informações):**
 - SO: win32 x64
 - Navegador: Chrome
 - Versão: 89.0.4389.90

**Comment by mariohmol** [comment]
uhmm se quer incluir o % na mascara?

vamos la

1. na validação ele ja aceita com ou sem o %  
- https://github.com/mariohmol/js-brasil/blob/master/test/validate.ts#L362

2. Hoje essa feature foi comentada
 - https://github.com/mariohmol/js-brasil/blob/master/src/mask.ts#L118

Acho que como porcentagem está praticamente igual ao number, vale a pena voltar a ter o sufixo

**Comment by mariohmol** [comment]
subi na nova versao 2.4.3

**Comment by JefersonDeSouza** [comment]
Muito obrigado pelo retorno Mario, vou atualizar a versão !
