### ISSUE TITLE
Máscara de Porcentagem - Limite de casas decimais

### ISSUE THREAD

**Issue by JefersonDeSouza** [mariohmol/ng-brazil#59]
**Descreva o bug**
Máscara para porcentagem não contém limite de casa decimal.

**Reproduzir**
Passos para reproduzir o comportamento:
1. Adicione ‘porcentagem [textMask]="{mask: MASKS.porcentagem.textMask}"’ no seu input text
2. Execute seu aplicativo
3. Veja o erro

**Comportamento esperado**
O comportamento esperado seria por exemplo 10 %, 30%, 100 %, ou 1.500 %, no entanto a máscara retorna nesse formato 10, 30, 100, 1.500.

**Capturas de tela**
 
![Screen Shot 03-23-21 at 02 22 PM](https://user-images.githubusercontent.com/25404751/112190361-af4f9f00-8be3-11eb-90d1-81629ba99595.PNG)

**Contexto adicional**
Angular CLI: 9.1.15
Node: 10.16.0
OS: win32 x64

Angular: 9.1.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.15
@angular-devkit/build-angular     0.901.15
@angular-devkit/build-optimizer   0.901.15
@angular-devkit/build-webpack     0.901.15
@angular-devkit/core              9.1.15
@angular-devkit/schematics        9.1.15
@angular/cli                      9.1.15
@angular/material                 9.2.4
@ngtools/webpack                  9.1.15
@schematics/angular               9.1.15
@schematics/update                0.901.15
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

**Desktop (preencha as seguintes informações):**
 - SO: win32 x64
 - Navegador: Chrome
 - Versão: 89.0.4389.90

**Comment by mariohmol** [comment]
como assim limite de casa decimal?

**Comment by JefersonDeSouza** [comment]
Não é possível limitar o tamanho do input, por exemplo imagine que eu o usuário digite 100%, porém ele também pode colocar 100000, e tem casos em que não faz sentido eu ter mais de 100% em algo.

**Comment by mariohmol** [comment]
coloca um max ou maxlength no input que deve resolver

**Comment by JefersonDeSouza** [comment]
Muito obrigado pelo help, vou fazer exatamente isso.
