### ISSUE TITLE
Inscrição Estadual Alagoas AL

### ISSUE THREAD

**Issue by alexandregyn** [mariohmol/ng-brazil#67]
A bilioteca está marcando como inválido a inscrição estadual de alagoas AL 24084153-0 sendo que ela 
é válida ao acessar o sintegra encontra a empresa de dessa inscrição informada.

https://sintegra.sefaz.al.gov.br/#/

**Comment by mariohmol** [comment]
Corrigido! Obrigado pelo alerta
