### ISSUE TITLE
Máscara / Validação de placa de carro novo padrão Mercosul

### ISSUE THREAD

**Issue by TeoDanilo** [mariohmol/ng-brazil#68]
**Is your feature request related to a problem? Please describe.**
A máscara e validação de placa de carro não permite o uso de letra no quinto caractere, como é o novo padrão

**Describe the solution you'd like**
Atualizar o repositório para suportar o novo padrão

**Additional context**
Padrão antigo (utilizado até agora pelo ng-brazil):
ABC-1234

Novo padrão Mercosul (utilizado oficialmente em todo Brasil)
ABC-1D23

Neste caso, o quinto elemento ('D') deveria ser tanto numero (para placas antigas) quanto letras (para placas novas)

**Comment by mariohmol** [comment]
Ola!

No JSBrasil já foi implementado o novo padrao, poderia pf verificar se está correto desta forma?

https://github.com/mariohmol/js-brasil/blob/master/test/validate.ts#L387

Att,
