### ISSUE TITLE
npm run start doesn't load. It just keeps Loading...

### ISSUE THREAD

**Issue by rogeriofonseca** [mariohmol/ng-brazil#70]
**Descrição do Problema**
Ao executar os passos na instrução do tópico **Collaborate** o projeto fica apresenta apenas a mensagem de **Loading...** e não carrega. Após o start o projeto aprenseta o index e após isso recarrea apresentando apenas a mensagem de **"Loading..."**

**Para reproduzir o problema**
Após executar os passos:
npm i -g rimraf ng-packagr @angular/compiler-cli @angular/compiler tslib ngc
npm i
npm run build:lib
npm run dist
**npm run start**

https://user-images.githubusercontent.com/1026153/132395501-c52a8f74-6b1c-42d8-8fab-775fe94c5f46.mp4

**Desktop Information and Versions:**
 - OS: OSX 11.5.2 Mac Big Sur
 - Node Version [v10.23.0]

**Comment by mariohmol** [comment]
Ola!
Obrigado por colaborar.. acabei de rodar aq e funcionou.. estou usando o node v18

consegue retestar pf? se persistir pode reabrir

abs

**Comment by rogeriofonseca** [comment]
> **npm run start**



> estou usando o node v18

Provavelmente o problema foi este. Acabei de rodar novamente com node na versão 18 e agora funcinou. Obrigado pela atenção.  👍
