### ISSUE TITLE
Angular 13 Support 

### ISSUE THREAD

**Issue by ariancruz** [mariohmol/ng-brazil#71]
npm i ng-brazil
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: linkapital-web-backoffice@0.0.0
npm ERR! Found: @angular/common@13.2.6
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=8.0.0 <13.0.0" from ng-brazil@2.4.5
npm ERR! node_modules/ng-brazil
npm ERR!   ng-brazil@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by ronelio** [comment]
I made some updates of dependencies.
Can you try from my repo? 
npm install git+https://github.com/ronelio/ng-brazil.git 

I'm testing with Angular 13 and if everything works fine, I'll open a PR.

**Comment by ronelio** [comment]
I use angular 13 and I forked this repository and update the dependencies to use angular 13.
**My fork:** 
https://github.com/ronelio/ng-brazil

**You can use the npm lib**
https://www.npmjs.com/package/@ronelio/ng-brazil

I didn't finish all the tests. You can use at your own risk.

When I think that my fork is stable enough, I'll open a PR to the original repo.

**Comment by mariohmol** [comment]
Hi! could u please provide a PR for us?

**Comment by ronelio** [comment]
Sure!

**Comment by mariohmol** [comment]
Hi there

release v2.5.0 with ang13 support!

Thanks @ronelio
