### ISSUE TITLE
[URGENCY] - Updade Angular v14

### ISSUE THREAD

**Issue by yvesguilherme** [mariohmol/ng-brazil#72]
Hey guys, I'm trying to update my project that uses this library to version 14.1.3, but I'm not succeeding. Could you please consider this issue? We Brazilians suffer with masks used in input forms...

_**One last question. Is the project abandoned?**_

Error log:

ng update @angular/core@14 @angular/cli@14
The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 14.1.3 to perform the update.
✔ Package successfully installed.
Using package manager: npm
Collecting installed dependencies...
Found 41 dependencies.
Fetching dependency metadata from registry...

- Package "ng-brazil" has an incompatible peer dependency to "@angular/common" (requires ">=8.0.0 <13.0.0" (extended), would install "14.1.3").

- Package "ng-brazil" has an incompatible peer dependency to "@angular/core" (requires ">=8.0.0 <13.0.0" (extended), would install "14.1.3").

- Package "ng-brazil" has an incompatible peer dependency to "@angular/platform-browser" (requires ">=8.0.0 <13.0.0" (extended), would install "14.1.3").

✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "/tmp/ng-GqDuP9/angular-errors.log" for further details.

**Comment by leonardopinheiromonteiro** [comment]
Hello everybody,

I had the same problem when a tried to install this package in my projetct. How can i solve this problem?

Best regards,

**Comment by ronelio** [comment]
Hey,
I'm using Angular 13 and I forked this repository and fixed the Angular 13 dependencies. Maybe it can help.
https://github.com/mariohmol/ng-brazil/issues/71

The tests isn't finished yet, but you can give a try.

**Comment by mariohmol** [comment]
@ronelio can u help us?

**Comment by ronelio** [comment]
Yes, I can. I'll check it out next week.

**Comment by yvesguilherme** [comment]
Any prediction? 😿

**Comment by HenriqueEichstadt** [comment]
Any prediction?

**Comment by yvesguilherme** [comment]
@ronelio any prediction?

**Comment by CristoferEichstadt** [comment]
Any prediction?

**Comment by rafastellato** [comment]
Hiii, any update? thanks

**Comment by mariohmol** [comment]
versao 3.0.0 com angular 14

feedback? =)
